connections {
    gw-gw {
        local_addrs  = 192.168.1.1
        remote_addrs = 192.168.1.2
        version = 2
        proposals = aes256gcm16-prfsha256-modp2048

        local {
            auth = psk
            id = gw-a
        }
        remote {
            auth = psk
            id = gw-b
        }

        children {
            net-net {
                local_ts  = 10.0.1.0/24
                remote_ts = 10.0.2.0/24
                esp_proposals = aes256gcm16-modp2048
                mode = tunnel
                start_action = trap
            }
        }
    }
}

secrets {
    ike-psk {
        id-a = gw-a
        id-b = gw-b
        secret = "super_secret_psk_123"
    }
}
