
connections {
    gw-gw {
        local_addrs  = 192.168.1.1
        remote_addrs = 192.168.1.2
        version = 1
        proposals = 3des-md5-modp1024

        local {
            auth = psk
            id = gateway-a
        }
        remote {
            auth = psk
            id = gateway-b
        }

        children {
            net-net {
                local_ts  = 10.0.1.0/24
                remote_ts = 10.0.2.0/24
                esp_proposals = 3des-md5
                mode = tunnel
                start_action = trap
            }
        }
    }
}

secrets {
    ike-psk {
        id-a = gateway-a
        id-b = gateway-b
        secret = "super_secret_psk_123"
    }
}
